### ISSUE TITLE
Model Features and Extensibility

### ISSUE THREAD

**Issue by hwhw97** [seemdog/ManWav#1]
This project is fantastic! I have a few questions:
	1.	Does it support streaming recognition?
	2.	What is the format of the transcription used for training?
	3.	If I want to fine-tune this model, is it supported? What format should the files be prepared in?

Looking forward to your response! Thank you!

**Comment by seemdog** [comment]
1, 3. ManWav is a Wav2Vec2-XLSR-53 fine-tuned with Manchu audio data and we uploaded the model in huggingface. You can use the model for any kind of usage you want.
2. Please refer to Section 3.2 in our paper(https://aclanthology.org/2024.fieldmatters-1.2.pdf).

**Comment by hwhw97** [comment]
Got it, thank you! 
It seems like a set of letters similar to IPA is being used. Does the ASR output also use this IPA-like transcription?

**Comment by seemdog** [comment]
Yes, once again, please refer to our paper for details.

**Comment by hwhw97** [comment]
> Yes, once again, please refer to our paper for details.

thank you!

**Comment by hwhw97** [comment]
Thanks！
