### ISSUE TITLE
About Model Usage,

### ISSUE THREAD

**Issue by hwhw97** [seemdog/ManWav#2]
```python
from transformers import AutoProcessor, AutoModelForCTC

processor = AutoProcessor.from_pretrained("seemdog/ManWav")
model = AutoModelForCTC.from_pretrained("seemdog/ManWav")
```

and

```python
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("automatic-speech-recognition", model="seemdog/ManWav")
```

What is the difference between these two approaches?

**Comment by seemdog** [comment]
The first one is loading the processor and model itself, but the second one is using the huggingface pipeline to use the model for the ASR task.

**Comment by hwhw97** [comment]
> The first one is loading the processor and model itself, but the second one is using the huggingface pipeline to use the model for the ASR task.

Thanks！
